JNG-4380 Upload and Download servlet name have to be defined to avoid…
BlackBeltTechnology/osgi-filestore pull request #53
Opened 2023-01-15 12:44 UTC by robertcsakany

… collosion because of the derived servlet name from class name

2023-01-16 22:41 UTC, bencegelei requested changes

2023-01-16 22:41 UTC, bencegelei commented on filestore-servlet/src/main/java/hu/blackbelt/osgi/filestore/servlet/DownloadServlet.java
> +Rdbms
I don't think this should be here:D

2023-01-18 17:20 UTC, robertcsakany commented on filestore-servlet/src/main/java/hu/blackbelt/osgi/filestore/servlet/DownloadServlet.java
> +Rdbms
nyehehe

2023-01-18 17:43 UTC, noherczeg approved these changes

2023-01-18 21:02 UTC, bencegelei approved these changes

2023-01-19 07:34 UTC, merged